name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  ci-tests:
    name: Tests unitaires (hors performance)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile project
        run: mvn clean install

      - name: Run unit tests (excluding performance)
        run: mvn test -Dtest=TestTourGuideService,TestRewardsService -DexcludeTests=TestPerformance

      - name: Build artifact
        run: mvn package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tourguide-artifact
          path: TourGuide/target/*.jar

  # Performance tests - track location
  performance-track-100:
    name: Performance Test - highVolumeTrackLocation with 100 users
    runs-on: ubuntu-latest
    needs: ci-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run highVolumeTrackLocation with 100 users
        run: mvn test -Dtest=TestPerformance#highVolumeTrackLocation -Duser.count=100

  performance-track-1000:
    name: Performance Test - highVolumeTrackLocation with 1000 users
    runs-on: ubuntu-latest
    needs: ci-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run highVolumeTrackLocation with 1000 users
        run:  mvn test -Dtest=TestPerformance#highVolumeTrackLocation -Duser.count=1000


  performance-track-10000:
    name: Performance Test - highVolumeTrackLocation with 10000 users
    runs-on: ubuntu-latest
    needs: ci-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run highVolumeTrackLocation with 10000 users
        run:  mvn test -Dtest=TestPerformance#highVolumeTrackLocation -Duser.count=10000


  performance-track-100000:
    name: Performance Test - highVolumeTrackLocation with 100000 users
    runs-on: ubuntu-latest
    needs: ci-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run highVolumeTrackLocation with 100000 users
        run: mvn test -Dtest=TestPerformance#highVolumeTrackLocation -Duser.count=100000

  # Performance tests - get rewards
  performance-rewards-100:
    name: Performance Test - highVolumeGetRewards with 100 users
    runs-on: ubuntu-latest
    needs: ci-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run highVolumeGetRewards with 100 users
        run: mvn test -Dtest=TestPerformance#highVolumeGetRewards -Duser.count=100

  performance-rewards-1000:
    name: Performance Test - highVolumeGetRewards with 1000 users
    runs-on: ubuntu-latest
    needs: ci-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run highVolumeGetRewards with 1000 users
        run:  mvn test -Dtest=TestPerformance#highVolumeGetRewards -Duser.count=1000

  performance-rewards-10000:
    name: Performance Test - highVolumeGetRewards with 10000 users
    runs-on: ubuntu-latest
    needs: ci-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run highVolumeGetRewards with 10000 users
        run: mvn test -Dtest=TestPerformance#highVolumeGetRewards -Duser.count=10000

  performance-rewards-100000:
    name: Performance Test - highVolumeGetRewards with 100000 users
    runs-on: ubuntu-latest
    needs: ci-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run highVolumeGetRewards with 100000 users
        run: mvn test -Dtest=TestPerformance#highVolumeGetRewards -Duser.count=100000
